SAGE-APP/Models/Projeto.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace SAGE_APP.Models
{
    [Table("Projetos")]
    public class Projeto
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Key]
        public int ProjetoId { get; set; }
        public int UserId { get; set; }
        public string Descricao { get; set; }
        public DateTime DataProva { get; set; }
        public int NumVagas { get; set; }
    }
}

SAGE-APP/Controllers/MateriaProjetosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SAGE_APP.Models;

namespace SAGE_APP.Controllers
{
    public class MateriaProjetosController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: MateriaProjetos
        //public ActionResult Index()
        //{
        //    return View(db.Materias.ToList());
        //}

        // GET: MateriaProjetos
        public ActionResult Index(string nomeProjeto)
        {
            string userName = null;
            int userId = 0;
            if (User.Identity.IsAuthenticated)
            {
                userName = User.Identity.Name;
                var usuariosLogado = db.Usuarios.Single(u => u.UserEmail.Equals(userName));
                userId = usuariosLogado.UserId;
            }
            else
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewBag.Projeto = nomeProjeto;
            var mat = db.MateriasProjetos.Select(m => m.MateriaId).ToList();
            var matPro = db.Materias.Select(mm => mm.Descricao).ToList();
            try
            {
                var listMP = new List<Tuple<int, string>>();
                var id = db.Projetos.Single(p => p.Descricao.Equals(nomeProjeto) && p.UserId == userId);
                ViewBag.ProjetoId = id.ProjetoId;
                var projetos = db.MateriasProjetos.Where(p => p.ProjetoId.Equals(id.ProjetoId)).ToArray();
                List<String> materiasProjeto = new List<string>();
                foreach (var item in projetos)
                {
                    var materiaDesc = db.Materias.Where(m => m.UserId == userId && m.MateriaId == item.MateriaId).Select(s => s.Descricao).ToList();
                    var materiaId = db.Materias.Where(m => m.UserId == userId && m.MateriaId == item.MateriaId).Select(s => s.MateriaId).ToList();
                    materiasProjeto.Add(materiaDesc[0]);
                    listMP.Add(Tuple.Create(materiaId[0], materiaDesc[0]));
                }
                //ViewBag.MateriasProjetos = materiasProjeto;
                ViewBag.MateriasProjetos = listMP;
            }
            catch (Exception)
            {
                //ViewBag.MateriasProjetos = new List<string>();
                ViewBag.MateriasProjetos = new List<Tuple<int, string>>();
            }

            //IList<SelectListItem> items = new List<SelectListItem>();
            //foreach (var item in matPro)
            //{
            //    items.Add(new SelectListItem { Text = item });
            //}
            ViewBag.Materias = new SelectList(db.Materias, "MateriaId", "Descricao"); ;
            //matPro = matPro.Contains(mat);
            return View(db.MateriasProjetos.ToList());
        }


        // GET: MateriaProjetos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MateriaProjeto materiaProjeto = db.MateriasProjetos.Find(id);
            if (materiaProjeto == null)
            {
                return HttpNotFound();
            }
            return View(materiaProjeto);
        }

        // GET: MateriaProjetos/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: MateriaProjetos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MateriaProjetoId,ProjetoId,MateriaId")] MateriaProjeto materiaProjeto)
        {
            if (ModelState.IsValid)
            {
                db.MateriasProjetos.Add(materiaProjeto);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(materiaProjeto);
        }

        // GET: MateriaProjetos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MateriaProjeto materiaProjeto = db.MateriasProjetos.Find(id);
            if (materiaProjeto == null)
            {
                return HttpNotFound();
            }
            return View(materiaProjeto);
        }

        // POST: MateriaProjetos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MateriaProjetoId,ProjetoId,MateriaId")] MateriaProjeto materiaProjeto)
        {
            if (ModelState.IsValid)
            {
                db.Entry(materiaProjeto).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(materiaProjeto);
        }

        // GET: MateriaProjetos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var materiaProjeto = db.MateriasProjetos.Single(m => m.MateriaId == id);
            if (materiaProjeto == null)
            {
                return HttpNotFound();
            }
            return View(materiaProjeto);
        }

        // POST: MateriaProjetos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int? id)
        {
            MateriaProjeto materiaProjeto = db.MateriasProjetos.Single(m => m.MateriaId == id);
            db.MateriasProjetos.Remove(materiaProjeto);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult AddMateria(int materia, int projeto)
        {
            if (ModelState.IsValid)
            {
                MateriaProjeto materiaProjeto = new MateriaProjeto
                {
                    MateriaId = materia,
                    ProjetoId = projeto
                };
                db.MateriasProjetos.Add(materiaProjeto);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

    }
}

SAGE-APP/Controllers/MateriasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SAGE_APP.Models;

namespace SAGE_APP.Controllers
{
    public class MateriasController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Materias
        public ActionResult Index()
        {
            return View(db.Materias.ToList());
        }

        // GET: Materias/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Materia materia = db.Materias.Find(id);
            if (materia == null)
            {
                return HttpNotFound();
            }
            return View(materia);
        }

        // GET: Materias/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Materias/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MateriaId,UserId,Descricao,Cor")] Materia materia)
        {
            if (ModelState.IsValid)
            {
                db.Materias.Add(materia);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(materia);
        }

        // GET: Materias/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Materia materia = db.Materias.Find(id);
            if (materia == null)
            {
                return HttpNotFound();
            }
            return View(materia);
        }

        // POST: Materias/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MateriaId,UserId,Descricao,Cor")] Materia materia)
        {
            if (ModelState.IsValid)
            {
                db.Entry(materia).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(materia);
        }

        // GET: Materias/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Materia materia = db.Materias.Find(id);
            if (materia == null)
            {
                return HttpNotFound();
            }
            return View(materia);
        }

        // POST: Materias/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Materia materia = db.Materias.Find(id);
            db.Materias.Remove(materia);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SAGE-APP/Controllers/ProjetosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SAGE_APP.Models;

namespace SAGE_APP.Controllers
{
    public class ProjetosController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Projetos
        public ActionResult Index()
        {
            return View(db.Projetos.ToList());
        }

        // GET: Projetos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Projeto projeto = db.Projetos.Find(id);
            if (projeto == null)
            {
                return HttpNotFound();
            }
            return View(projeto);
        }

        // GET: Projetos/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Projetos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProjetoId,UserId,Descricao,DataProva,NumVagas")] Projeto projeto)
        {
            if (ModelState.IsValid)
            {
                db.Projetos.Add(projeto);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(projeto);
        }

        // GET: Projetos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Projeto projeto = db.Projetos.Find(id);
            if (projeto == null)
            {
                return HttpNotFound();
            }
            return View(projeto);
        }

        // POST: Projetos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProjetoId,UserId,Descricao,DataProva,NumVagas")] Projeto projeto)
        {
            if (ModelState.IsValid)
            {
                db.Entry(projeto).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(projeto);
        }

        // GET: Projetos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Projeto projeto = db.Projetos.Find(id);
            if (projeto == null)
            {
                return HttpNotFound();
            }
            return View(projeto);
        }

        // POST: Projetos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Projeto projeto = db.Projetos.Find(id);
            db.Projetos.Remove(projeto);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SAGE-APP/Views/Projetos/Create.cshtml
@model SAGE_APP.Models.Projeto

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Projeto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="form-group">
            @Html.LabelFor(model => model.UserId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataProva, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataProva, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataProva, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumVagas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumVagas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumVagas, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SAGE-APP/Views/Projetos/Delete.cshtml
@model SAGE_APP.Models.Projeto

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Projeto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataProva)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataProva)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumVagas)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumVagas)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SAGE-APP/Views/Projetos/Details.cshtml
@model SAGE_APP.Models.Projeto

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Projeto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataProva)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataProva)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumVagas)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumVagas)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ProjetoId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SAGE-APP/Views/Projetos/Edit.cshtml
@model SAGE_APP.Models.Projeto

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Projeto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ProjetoId)

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataProva, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataProva, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataProva, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumVagas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumVagas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumVagas, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SAGE-APP/Views/Projetos/Index.cshtml
@model IEnumerable<SAGE_APP.Models.Projeto>

@{
    ViewBag.Title = "Projetos - SAGE";
}

<h2>Projetos</h2>

<div style="width: 100%; display: flex; justify-content: flex-end;">
    <div style="width: 50%; float: left;">
        @Html.ActionLink("Create New", "Create")
    </div>
    <div style="margin-left:auto; margin-right:0;">
        @Html.ActionLink("Gerenciar matérias", "Index", "Materias")
    </div>
</div>
<p></p>
<table class="table">
    <tr>
        @*<th>
            @Html.DisplayNameFor(model => model.UserId)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.Descricao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DataProva)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NumVagas)
        </th>
        <th></th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        @*<td>
            @Html.DisplayFor(modelItem => item.UserId)
        </td>*@
        <td>
            @Html.DisplayFor(modelItem => item.Descricao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DataProva)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NumVagas)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id=item.ProjetoId }) |
            @Html.ActionLink("Detalhes", "Details", new { id=item.ProjetoId }) |
            @Html.ActionLink("Excluir", "Delete", new { id=item.ProjetoId })
        </td>
        <td>
            @Html.ActionLink("Matérias", "Index", "MateriaProjetos", new { nomeProjeto = item.Descricao }, null)
        </td>
    </tr>
}

</table>